-- MySQL Script generated by MySQL Workbench
-- Fri 06 Jan 2017 12:08:41 PM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testTask
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testTask
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testTask` DEFAULT CHARACTER SET utf8 ;
USE `testTask` ;

-- -----------------------------------------------------
-- Table `testTask`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testTask`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `id_user` INT NOT NULL,
  `like` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_UNIQUE` (`id_user` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `testTask`.`repos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testTask`.`repos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_repo` INT NOT NULL,
  `like` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_repo_UNIQUE` (`id_repo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
